apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  selector:
    app: kubetask
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetask
  template:
    metadata:
      labels:
        app: kubetask
    spec:
      containers:
      - name: frontend
        image: berndtzayne/nodeexpress
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
        - name: hostname #double check name
          mountPath: /root/key.json
          subPath: key.json
        env:
        - name: #double check this
          valueFrom:
            secretKeyRef:
              name: hostname-be-b
              key: hostnameb
      volumes:
      - name: #double check this
        secret:
          secretName: hostname-be-a
          items:
          - key: hostname
            path: key.json
