apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a
spec:
  selector:
    matchLabels:
      app: kubetask
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: kubetask
        tier: backend
        track: stable
    spec:
      containers:
        - name:
          image: berndtzayne/nodereq
          ports:
            - name: http
              containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  selector:
    app: hello #uses selector labels to link to frontend
    tier: backend #uses selector labels to link to frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
