apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetask
  template:
    metadata:
      labels:
        app: kubetask
    spec:
      containers:
      - name: backendb
        image: berndtzayne/nodeexpress
        ports:
          - name: http
            containerPort: 80
          volumeMounts:
            - mountPath: /foo
              name:
          volumes:
            - name:
              PersistentVolumeClaim:
                claimName: kubetask-pvc-b
          ports:
            - name: http
              containerPort: 80
