apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b
spec:
  selector:
    matchLabels:
      app: kubetask
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: kubetask
        tier: backend
        track: stable
    spec:
      containers:
        - name:
          image: berndtzayne/nodereq
          ports:
            - name: http
              containerPort: 80
      volumeMounts:
        - mountPath: "add some nfs storage path"
          name: task-pv-storage

---
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  selector:
    app: hello #uses selector labels to link to frontend
    tier: backend #uses selector labels to link to frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
