apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenda-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubetask
      tier: backend
  template:
    metadata:
      labels:
        app: kubetask
    spec:
      containers:
      - name: backenda
        image: berndtzayne/nodeexpress
        ports:
          - name: http
            containerPort: 80
          volumeMounts:
            - mountPath: /foo
              name:
          volumes:
            - name:
              PersistentVolumeClaim:
                claimName: kubetask-pvc-a
          ports:
            - name: http
              containerPort: 80
