apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubetask-pv-a
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: kubetask-a
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  #I am guessing the path would be something like this using nfs or whatever lloyds use.
  # nfs:
  #   path: /opt/nfs
  #   server: nfs.f22
  #   readOnly: false

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubetask-pv-a
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: kubetask-a
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  #I am guessing the path would be something like this using nfs or whatever lloyds use.
  # nfs:
  #   path: /opt/nfs
  #   server: nfs.f22
  #   readOnly: false
